services:
  minio: 
    image: minio/minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    command: server /data --console-address ':9001'

