# version: '2.27'

services:
  airflow-container:
    build: 
      context: .
      dockerfile: Dockerfile.airflow
    restart: always
    volumes:
      - ./data:/opt/airflow/data
      - ./dags:/opt/airflow/dags
      - ./s3_bucket/s3_bucket.py:/opt/airflow/s3_bucket.py
      - ./airflow-infor:/opt/airflow
      - ./.env:/opt/airflow/.env
    ports:
      - 8080:8080
    command: bash -c '(airflow db init && airflow users create --username ${AIRFLOW_USER_NAME} --password ${AIRFLOW_USER_PASSWORD} --firstname ${AIRFLOW_USER_FIRSTNAME} --lastname ${AIRFLOW_USER_LASTNAME} --role Admin --email ${AIRFLOW_USER_EMAIL}); airflow webserver & airflow scheduler'
  dash-app:
    build:
      context: .
      dockerfile: ./visualization/Dockerfile.dash
    restart: always
    volumes:
      - ./visualization:/visualization
      - ./.env:/opt/.env
    ports:
      - 8050:8050
  

volumes:
  dags:
  data:
  visualization:
  airflow-infor: